---
repos: 
  - repo: https://github.com/ansible-community/ansible-lint.git
    rev: v6.6.0
    hooks:
      - id: ansible-lint
        files: \.(yaml|yml)$
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.28.0
    hooks:
      - id: yamllint