---
- name: Get the path to ZSH
  become: false
  changed_when: false
  command: which zsh
  register: zsh_path

- name: "Ensure homebrew zsh is in allowed shells"
  lineinfile:
    path: /etc/shells
    line: "{{ zsh_path.stdout }}"
  become: true

- name: Install Oh My ZSH
  changed_when: false
  command: sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
  args:
    creates: "/Users/{{ lookup('env', 'USER') }}/.oh-my-zsh"

- name: Set ZSH as the default shell
  changed_when: false
  command: chsh -s $(which zsh) {{ lookup('env', 'USER') }}
  become: true

# - name: "Create a default ZSH configuration"
#   template:
#     src: templates/.zshrc.j2
#     dest: /Users/{{ lookup('env', 'USER') }}/.zshrc
#     owner: "{{ lookup('env', 'USER') }}"
#     force: yes  